### ISSUE TITLE
Reorganize utils

### ISSUE THREAD

**Issue by MSevey** [SkynetHQ/skynet-js#3]
<a href="https://github.com/m-cat"><img src="https://avatars.githubusercontent.com/u/6035856?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [m-cat](https://github.com/m-cat)**
_Wednesday Nov 11, 2020 at 16:58 GMT_
_Originally opened as https://github.com/NebulousLabs/skynet-js/issues/183_

----

The `utils.ts` file is stuffed with a bunch of different functions by this point. I think it would be itneresting to organize them into a `utils` directory with different files (for example, theres a few functions for manipulating URLs that can go into `utils/url.ts`).

**Comment by MSevey** [comment]
<a href="https://github.com/emersonmacro"><img src="https://avatars.githubusercontent.com/u/77563348?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [emersonmacro](https://github.com/emersonmacro)**
_Monday Mar 15, 2021 at 06:34 GMT_

----

Hello, I'm new to Skynet but I'm interested in getting more involved. Made a PR for this issue - feedback welcome.

**Comment by m-cat** [comment]
Closed in nebulouslabs/skynet-js#364
